### ISSUE TITLE
tst.server.js fails after #14

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-fast#19]
On master:

```
$ make prepush
jsl --nologo --nosummary --conf=tools/jsl.node.conf bin/fastbench bin/fastcall bin/fastserve lib/fast_client_request.js lib/fast_protocol.js lib/subr.js lib/bench.js lib/fast.js lib/fast_client.js lib/demo_server.js lib/fast_server.js test/tst.client_request.js test/tst.allocator.js test/common.js test/tst.protocol_decoder.js test/tst.client_generic.js test/tst.protocol_encoder.js test/compat/legacy-server.js test/compat/manual-tst.client_compat.js test/compat/common.js test/compat/setup.js test/tst.server.js test/tst.socket_summarize.js test/common/client.js
/home/dap/node-fast/bin/fastbench
/home/dap/node-fast/bin/fastcall
/home/dap/node-fast/bin/fastserve
/home/dap/node-fast/lib/fast_client_request.js
/home/dap/node-fast/lib/fast_protocol.js
/home/dap/node-fast/lib/subr.js
/home/dap/node-fast/lib/bench.js
/home/dap/node-fast/lib/fast.js
/home/dap/node-fast/lib/fast_client.js
/home/dap/node-fast/lib/demo_server.js
/home/dap/node-fast/lib/fast_server.js
/home/dap/node-fast/test/tst.client_request.js
/home/dap/node-fast/test/tst.allocator.js
/home/dap/node-fast/test/common.js
/home/dap/node-fast/test/tst.protocol_decoder.js
/home/dap/node-fast/test/tst.client_generic.js
/home/dap/node-fast/test/tst.protocol_encoder.js
/home/dap/node-fast/test/compat/legacy-server.js
/home/dap/node-fast/test/compat/manual-tst.client_compat.js
/home/dap/node-fast/test/compat/common.js
/home/dap/node-fast/test/compat/setup.js
/home/dap/node-fast/test/tst.server.js
/home/dap/node-fast/test/tst.socket_summarize.js
/home/dap/node-fast/test/common/client.js
json --validate -f package.json
jsstyle  bin/fastbench bin/fastcall bin/fastserve lib/fast_client_request.js lib/fast_protocol.js lib/subr.js lib/bench.js lib/fast.js lib/fast_client.js lib/demo_server.js lib/fast_server.js test/tst.client_request.js test/tst.allocator.js test/common.js test/tst.protocol_decoder.js test/tst.client_generic.js test/tst.protocol_encoder.js test/compat/legacy-server.js test/compat/manual-tst.client_compat.js test/compat/common.js test/compat/setup.js test/tst.server.js test/tst.socket_summarize.js test/common/client.js
check ok
deps/catest/catest test/tst.client_request.js test/tst.allocator.js test/tst.protocol_decoder.js test/tst.client_generic.js test/tst.protocol_encoder.js test/tst.server.js test/tst.socket_summarize.js
Configuration:
    SRC:                         /home/dap/node-fast
    Output directory:            /var/tmp/catest.586
    Temp directory:              /var/tmp/catest.586_tmpfiles
    Keep successful test output: false
    Found 7 test(s) to run

===================================================

Executing test test/tst.client_request.js ... success.
Executing test test/tst.allocator.js ... success.
Executing test test/tst.protocol_decoder.js ... success.
Executing test test/tst.client_generic.js ... success.
Executing test test/tst.protocol_encoder.js ... success.
Executing test test/tst.server.js ... FAILED.
>>> failure details in /var/tmp/catest.586/failure.0

Executing test test/tst.socket_summarize.js ... success.

===================================================

Results:
        Tests passed:    6/ 7
        Tests failed:    1/ 7

===================================================
Cleaning up output from successful tests ... done.
make: *** [test] Error 1
dap@b44c74d6 node-fast $ cat /var/tmp/catest.586/failure.0/README 
/home/dap/node-fast/test/tst.server.js failed: test returned 8
dap@b44c74d6 node-fast $ cat /var/tmp/catest.586/failure.0/*.err
test case: basic RPC: no data
test case: basic RPC: 1 data item
test case: basic RPC: several data items
test case: basic RPC: 0 data items, plus error
test case: basic RPC: several data items, plus error
test case: RPC for non-existent method
test case: multiple RPCs for the same client run in parallel
test case: connection error with requests outstanding: protocol error
test case: connection error with requests outstanding: socket error
test case: connection error followed by server shutdown
test case: basic RPC with immediate end-of-stream
test case: RPC with large amount of data
test case: flow control from server to client
test case: 'onConnsDestroyed' callback test
test case: 'onConnsDestroyed' callback after successful rpc
test case: 'onConnsDestroyed' callback after protocol error
test case: 'onConnsDestroyed' multiple callbacks queued
test case: 'onConnsDestroyed' callback after many requests

/home/dap/node-fast/test/tst.server.js:1125
                var e = new EventEmitter();
                        ^
TypeError: object is not a function
    at /home/dap/node-fast/test/tst.server.js:1125:11
    at Socket.<anonymous> (/home/dap/node-fast/test/tst.server.js:89:3)
    at Socket.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:887:10)
```

This appears to have been introduced with #14.  @IanWyszynski, can you take a look when you get a chance?

**Comment by melloc** [comment]
This is caused by:

```javascript
var EventEmitter = require('events');
```

In node v0.10, this is just an object, but later versions made it a constructor, too:

```
cody@101901c9-6d66-ea32-fe42-f1fbebd4bf99 ~ (1) % ~/node-versions/node-v4.8.1-sunos-x86/bin/node -e 'console.log(require("events"))'
{ [Function: EventEmitter]
  EventEmitter: [Circular],
  usingDomains: false,
  defaultMaxListeners: 10,
  init: [Function],
  listenerCount: [Function] }
cody@101901c9-6d66-ea32-fe42-f1fbebd4bf99 ~ % ~/node-versions/node-v0.10.47-sunos-x86/bin/node -e 'console.log(require("events"))' 
{ usingDomains: false,
  EventEmitter: { [Function: EventEmitter] listenerCount: [Function] } }
```

**Comment by IanWyszynski** [comment]
With the change here: https://cr.joyent.us/#/c/3989/, the test suite passes for node v10 as well as v4. Instead of using a separate EventEmitter, the test now simply closes the queue once all RPCs have been sent and completed. This allows us to later handle the node-vasync 'end' event, which the call to close triggers.
